apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-web-chart
  name: nginx-web-chart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-web-chart
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-web-chart
    spec:
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: nginx
        resources: {}
